#!/usr/bin/env bash

# If script is passed parameter "local", runs the script locally
where_to_run=$1

# Setting folder variables
src_files="/autograder/source/"
subm_files="/autograder/submission/"
results="/autograder/results/"
#subm_files="/home/pranjalravi/project_1_d/subm/"
#results="/home/pranjalravi/project_1_d/results/"
#src_files="/home/pranjalravi/project_1_d/"
package="edu/tamu/csce434"

cd ${src_files}
# make it local
if [ "$where_to_run" == "local" ]
then
    src_files=".${src_files}"
    subm_files=".${subm_files}"
    results=".${results}"
fi

cd ${src_files}
chmod -R 775 ${subm_files}/*
cp -rf ${subm_files}/* ${package}/
numTest=`ls Tests/* | wc -l`
cp -f TestCompiler.java ${package}/

if  javac ${package}/*.java
then
  rm -rf Out
  mkdir Out
  rm -rf Out_bk
  mkdir Out_bk
  i=1

  for file in `ls Tests/*`
  do
    timeout 30s java ${package}/TestCompiler "Tests/test_${i}" "TestInputs/tests_${i}.in" > "Out_bk/out_${i}" 2> "Out/err_${i}"
    i=$((i+1))
  done
  bash segregate_data.sh 
  python3 compare.py $results $numTest
else
  rm -f ${package}/*.class
  javac ${package}/*.java 2>&1 | tee javac_output  
  python3 failed.py $results $numTest
fi
